all: build

build:
	+$(MAKE) -C	Item
	+$(MAKE) -C	Coconut
	+$(MAKE) -C	Leafs
	+$(MAKE) -C	Lighter
	+$(MAKE) -C	Rock
	+$(MAKE) -C	WoodStick
	+$(MAKE) -C	Axe
	+$(MAKE) -C	Hut
	+$(MAKE) -C	OpenCoconut
	+$(MAKE) -C	LightedTorch
