.TH "Coconut" 3 "Σαβ 06 Ιουν 2020" "Version Alpha" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Coconut
.SH SYNOPSIS
.br
.PP
.PP
Κληρονομεί την \fBItem\fP\&.
.SS "Δημόσιες Μέθοδοι"

.in +1c
.ti -1c
.RI "\fBCoconut\fP (string name, string id, \fBVector2D\fP< int >pos, bool isOnFloor=true)"
.br
.ti -1c
.RI "\fBCoconut\fP (const \fBCoconut\fP &copy)"
.br
.in -1c

.SH "Συγραφέας"
.PP 
Δημιουργήθηκε αυτόματα από το Doxygen για My Project από τον πηγαίο κώδικα\&.
