.TH "IO/csv_parser.cpp" 3 "Παρ 05 Ιουν 2020" "Version Alpha" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IO/csv_parser.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iterator>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br

.SS "Κλάσεις"

.in +1c
.ti -1c
.RI "class \fBCSVRow\fP"
.br
.in -1c
.SS "Συναρτήσεις"

.in +1c
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &str, \fBCSVRow\fP &data)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Τεκμηρίωση Συναρτήσεων"
.PP 
.SS "int main ()"

.SS "std::istream& operator>> (std::istream & str, \fBCSVRow\fP & data)"

.SH "Συγραφέας"
.PP 
Δημιουργήθηκε αυτόματα από το Doxygen για My Project από τον πηγαίο κώδικα\&.
