.TH "CSVRow" 3 "Παρ 05 Ιουν 2020" "Version Alpha" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSVRow
.SH SYNOPSIS
.br
.PP
.SS "Δημόσιες Μέθοδοι"

.in +1c
.ti -1c
.RI "std::string const  & \fBoperator[]\fP (std::size_t index) const"
.br
.ti -1c
.RI "std::size_t \fBsize\fP () const"
.br
.ti -1c
.RI "void \fBreadNextRow\fP (std::istream &str)"
.br
.ti -1c
.RI "std::string const  & \fBoperator[]\fP (std::size_t index) const"
.br
.ti -1c
.RI "std::size_t \fBsize\fP () const"
.br
.ti -1c
.RI "void \fBreadNextRow\fP (std::istream &str)"
.br
.in -1c

.SH "Συγραφέας"
.PP 
Δημιουργήθηκε αυτόματα από το Doxygen για My Project από τον πηγαίο κώδικα\&.
