.TH "GameScene" 3 "Δευ 08 Ιουν 2020" "Version Alpha" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameScene
.SH SYNOPSIS
.br
.PP
.SS "Δημόσιες Μέθοδοι"

.in +1c
.ti -1c
.RI "\fBGameScene\fP (\fBIoClass\fP *ioManager, \fBEnvironment\fP *env)"
.br
.ti -1c
.RI "\fBGameScene\fP (const \fBGameScene\fP &copy)"
.br
.ti -1c
.RI "GameState \fBgetState\fP ()"
.br
.ti -1c
.RI "void \fBcheckHunger\fP (chrono::minutes::rep &, chrono::_V2::system_clock::time_point &)"
.br
.ti -1c
.RI "void \fBsetState\fP (GameState state)"
.br
.ti -1c
.RI "string \fBstartupScreen\fP ()"
.br
.ti -1c
.RI "void \fBPlay\fP ()"
.br
.ti -1c
.RI "void \fBparseSelection\fP (int c)"
.br
.ti -1c
.RI "void \fBhandleMainMenu\fP (int menuSelection)"
.br
.ti -1c
.RI "void \fBhandleInventoryMenu\fP (int menuSelection)"
.br
.ti -1c
.RI "void \fBhandleCraftingMenu\fP (int menuSelection)"
.br
.ti -1c
.RI "void \fBhandleEndingMenu\fP (int menuSelection)"
.br
.in -1c

.SH "Συγραφέας"
.PP 
Δημιουργήθηκε αυτόματα από το Doxygen για My Project από τον πηγαίο κώδικα\&.
