.TH "GameScene/GameScene.h" 3 "Παρ 05 Ιουν 2020" "Version Alpha" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameScene/GameScene.h
.SH SYNOPSIS
.br
.PP
\fC#include <chrono>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Κλάσεις"

.in +1c
.ti -1c
.RI "class \fBGameScene\fP"
.br
.in -1c
.SS "Απαριθμήσεις"

.in +1c
.ti -1c
.RI "enum \fBGameState\fP { \fBinitializing\fP, \fBwaiting\fP, \fBrunning\fP, \fBsaving\fP, \fBloading\fP, \fBexiting\fP }"
.br
.in -1c
.SH "Τεκμηρίωση Απαριθμήσεων"
.PP 
.SS "enum \fBGameState\fP"

.PP
\fBΤιμές Απαριθμήσεων\fP
.in +1c
.TP
\fB\fIinitializing \fP\fP
.TP
\fB\fIwaiting \fP\fP
.TP
\fB\fIrunning \fP\fP
.TP
\fB\fIsaving \fP\fP
.TP
\fB\fIloading \fP\fP
.TP
\fB\fIexiting \fP\fP
.SH "Συγραφέας"
.PP 
Δημιουργήθηκε αυτόματα από το Doxygen για My Project από τον πηγαίο κώδικα\&.
