.TH "IO/IoClass.h" 3 "Παρ 05 Ιουν 2020" "Version Alpha" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IO/IoClass.h
.SH SYNOPSIS
.br
.PP
\fC#include <ncurses\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include '\&.\&./Player/Player\&.h'\fP
.br

.SS "Κλάσεις"

.in +1c
.ti -1c
.RI "class \fBIoClass\fP"
.br
.in -1c
.SH "Συγραφέας"
.PP 
Δημιουργήθηκε αυτόματα από το Doxygen για My Project από τον πηγαίο κώδικα\&.
