.TH "Leafs" 3 "Παρ 19 Ιουν 2020" "Version Alpha" "Adventure Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leafs \- Κλάση αντικειμένου \fBLeafs\fP 
.br
 Χρησιμοποιείται για τα συμβολίσει Φύλλο  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Leafs\&.h>\fP
.PP
Κληρονομεί την \fBItem\fP\&.
.SS "Δημόσιες Μέθοδοι"

.in +1c
.ti -1c
.RI "\fBLeafs\fP (string name, string id, \fBVector2D\fP< int >pos, bool isOnFloor=true)"
.br
.ti -1c
.RI "\fBLeafs\fP (const \fBLeafs\fP &copy)"
.br
.in -1c
.SH "Λεπτομερής Περιγραφή"
.PP 
Κλάση αντικειμένου \fBLeafs\fP 
.br
 Χρησιμοποιείται για τα συμβολίσει Φύλλο 

.SH "Συγραφέας"
.PP 
Δημιουργήθηκε αυτόματα από το Doxygen για Adventure Game από τον πηγαίο κώδικα\&.
