.TH "LightedTorch" 3 "Δευ 08 Ιουν 2020" "Version Alpha" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LightedTorch \- Κλάση αντικειμένου \fBLightedTorch\fP 
.br
 Χρησιμοποιείται για τα συμβολίσει αναμμένο πυρσό\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LightedTorch\&.h>\fP
.PP
Κληρονομεί την \fBItem\fP\&.
.SS "Δημόσιες Μέθοδοι"

.in +1c
.ti -1c
.RI "\fBLightedTorch\fP (string name, string id, \fBVector2D\fP< int >pos, bool isOnFloor=true)"
.br
.ti -1c
.RI "\fBLightedTorch\fP (const \fBLightedTorch\fP &copy)"
.br
.in -1c
.SH "Λεπτομερής Περιγραφή"
.PP 
Κλάση αντικειμένου \fBLightedTorch\fP 
.br
 Χρησιμοποιείται για τα συμβολίσει αναμμένο πυρσό\&. 

.SH "Συγραφέας"
.PP 
Δημιουργήθηκε αυτόματα από το Doxygen για My Project από τον πηγαίο κώδικα\&.
