.TH "Lighter" 3 "Παρ 05 Ιουν 2020" "Version Alpha" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lighter
.SH SYNOPSIS
.br
.PP
.PP
Κληρονομεί την \fBItem\fP\&.
.SS "Δημόσιες Μέθοδοι"

.in +1c
.ti -1c
.RI "\fBLighter\fP (string name, string id, \fBVector2D\fP< int >pos, bool isOnFloor=true)"
.br
.ti -1c
.RI "\fBLighter\fP (const \fBLighter\fP &copy)"
.br
.in -1c

.SH "Συγραφέας"
.PP 
Δημιουργήθηκε αυτόματα από το Doxygen για My Project από τον πηγαίο κώδικα\&.
