.TH "main.cpp" 3 "Παρ 05 Ιουν 2020" "Version Alpha" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'Player/Player\&.h'\fP
.br
\fC#include 'Items/Item/Item\&.h'\fP
.br
\fC#include 'Inventory/Inventory\&.h'\fP
.br
\fC#include 'Items/Coconut/Coconut\&.h'\fP
.br
\fC#include 'Items/Rock/Rock\&.h'\fP
.br
\fC#include 'Environment/Environment\&.h'\fP
.br
\fC#include 'GameScene/GameScene\&.h'\fP
.br

.SS "Συναρτήσεις"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &s, \fBPlayer\fP p)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Τεκμηρίωση Συναρτήσεων"
.PP 
.SS "int main ()"

.SS "ostream& operator<< (ostream & s, \fBPlayer\fP p)"

.SH "Συγραφέας"
.PP 
Δημιουργήθηκε αυτόματα από το Doxygen για My Project από τον πηγαίο κώδικα\&.
