.TH "Player/Player.cpp" 3 "Παρ 05 Ιουν 2020" "Version Alpha" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player/Player.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Player\&.h'\fP
.br
\fC#include '\&.\&./Vector2D/Vector2D\&.h'\fP
.br
\fC#include '\&.\&./Inventory/Inventory\&.h'\fP
.br
\fC#include '\&.\&./Items/Item/Item\&.h'\fP
.br
\fC#include '\&.\&./Items/LightedTorch/LightedTorch\&.h'\fP
.br
\fC#include '\&.\&./Items/OpenCoconut/OpenCoconut\&.h'\fP
.br
\fC#include '\&.\&./DynamicArray/DynamicArray\&.h'\fP
.br
\fC#include '\&.\&./Items/Axe/Axe\&.h'\fP
.br

.SS "Συναρτήσεις"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, \fBItem\fP item)"
.br
.in -1c
.SH "Τεκμηρίωση Συναρτήσεων"
.PP 
.SS "ostream& operator<< (ostream & os, \fBItem\fP item)"

.SH "Συγραφέας"
.PP 
Δημιουργήθηκε αυτόματα από το Doxygen για My Project από τον πηγαίο κώδικα\&.
