.TH "Vector2D/Vector2D.h" 3 "Παρ 05 Ιουν 2020" "Version Alpha" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vector2D/Vector2D.h
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br

.SS "Κλάσεις"

.in +1c
.ti -1c
.RI "class \fBVector2D< T >\fP"
.br
.in -1c
.SS "Ορισμοί Τύπων"

.in +1c
.ti -1c
.RI "typedef \fBVector2D\fP< int > \fBVector2Di\fP"
.br
.ti -1c
.RI "typedef \fBVector2D\fP< double > \fBVector2Dd\fP"
.br
.in -1c
.SH "Τεκμηρίωση Ορισμών Τύπων"
.PP 
.SS "typedef \fBVector2D\fP<double> \fBVector2Dd\fP"

.SS "typedef \fBVector2D\fP<int> \fBVector2Di\fP"

.SH "Συγραφέας"
.PP 
Δημιουργήθηκε αυτόματα από το Doxygen για My Project από τον πηγαίο κώδικα\&.
