.TH "Items/WoodStick/WoodStick.h" 3 "Παρ 05 Ιουν 2020" "Version Alpha" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Items/WoodStick/WoodStick.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./Item/Item\&.h'\fP
.br
\fC#include '\&.\&./Rock/Rock\&.h'\fP
.br
\fC#include '\&.\&./Axe/Axe\&.h'\fP
.br

.SS "Κλάσεις"

.in +1c
.ti -1c
.RI "class \fBWoodStick\fP"
.br
.in -1c
.SH "Συγραφέας"
.PP 
Δημιουργήθηκε αυτόματα από το Doxygen για My Project από τον πηγαίο κώδικα\&.
